### ISSUE TITLE
JavaFX frontend

### ISSUE THREAD

**Issue by PatrykZaniewski** [PatrykZaniewski/TestDrivenDevelopmentProject#3]

**Comment by maciekkoz98** [comment]
asdasd

**Comment by PatrykZaniewski** [comment]
Pole klucz musi być zależne od wybranego szyfrowania, tj. nie może być tak, że (( ͡° ͜ʖ ͡°)) jak ktoś wybierze ROT13 albo RSA to dalej ma podać klucz. Przy takim wyborze musi pokazać się inne pole czyli dla ROT13 przesunięcie, a dla RSA dwa pola z prośbą o p i q. 

Do filechooserów trzeba dorobić żeby mogło tylko konkretne rozszerzenia plików otwierać.

**Comment by PatrykZaniewski** [comment]
Okienko nie skaluje się prawidłowo, więc albo poprawiamy to albo blokujemy zmianę rozmiaru,

**Comment by maciekkoz98** [comment]
Ja bym pozostał przy jednym rozmiarze, żeby nie babrać się z jakimiś skalowaniami

**Comment by maciekkoz98** [comment]
Myślę, że przy RSA to raczej powinna być prośba o klucz publiczny niż o liczby.
Kodujemy przecież w oparciu o klucz publiczny, otrzymamy plik możemy odkodować tylko w oparciu o klucz prywatny. 
Generację kluczy można rozwiać przez zew program (np. puTTY key gen)

**Comment by PatrykZaniewski** [comment]
Tylko jedyne co mnie boli z tym RSA to to, że te klucze są mega długie i czy to jest dobre podejście żeby kopiować to właśnie tak. Nie wiem czy nie byłob lepiej podawać te 3 liczby potrzebne do RSA.

**Comment by PatrykZaniewski** [comment]
Jak ktoś ma jakiś pomysł jak ładnie zrobić kod do przycisków szyfrowania i deszyfrowania to zapraszam. Aktualnie na chama go przekopiowałem po prostu :|.

**Comment by PatrykZaniewski** [comment]
Sprawdzanie z komunikatem czy klucz w ROT jest liczbą. 

Podmianka rozszerzeń -> w szyfrowaniu szukamy tylko txt, a w deszyfrowaniu tylko json. 

Sprawdzanie plików przy wciskaniu przycisku. Teraz jest tak, że jak sobie usunę deletem ścieżkę to i tak mnie przepuszcza. Prawdopodobnie chodzi o to, że ten tekst jest tylko tekstem, a nie rzeczywistym wskazaniem na ścieżkę. Może zablokujemy edycję tych pól dla użytkownika? Będzie mógł tylko wybrać plik poprzez przycisk.

Blokada co do długości klucza -> zakomentowałem aktualnie bo te biblioteki sobie magicznie dopełniają klucze jakoś XD.

**Comment by KatarzynaWolska** [comment]
Wydaje się, że wszystko poprawiłam. Dodałam też w dekryptowaniu zmianę labela "Klucz" na "Przesunięcie" dla ROT gdy użytkownik wybierze plik. Na razie po prostu wyszukuję czy ścieżka do pliku zawiera string "ROT", ale gdy użytkownik zmieni nazwę pliku to już nie będzie działać. Zastanawiam się czy w takim razie otwierać jeszcze raz w innej metodzie tego JSONa i w nim sprawdzać jakim algorytmem zostało zaszyfrowane, czy zostawić tak jak jest ;P

**Comment by PatrykZaniewski** [comment]
Właśnie dlatego myślałem nad zablokowaniem tego labela żeby użytkownik nie mógł edytować.

**Comment by KatarzynaWolska** [comment]
Spoko, tylko co jeśli użytkownik zmieni nazwę pliku "poza" aplikacją. W sensie, że np. ma ten plik zapisany dajmy na to na pulpicie i tam zmienia jego nazwę? To wtedy blokada tego pola nic nie daje. Chyba, że coś źle kumam XD

**Comment by PatrykZaniewski** [comment]
Ale to chyba nawet nie da rady z tym zawalczyć wtedy. Byleby tylko było zablokowane, że pisać ani usuwać tam nic nie może i będzie git myślę.

**Comment by KatarzynaWolska** [comment]
No dobra, to w takim razie blokujemy.
